version: "3"

services:
  web:
    image: php:8.0.1-apache
    restart: always
    container_name: php_web_electracker
    volumes:
      - ./html:/var/www/html/
    ports:
      - "8200:80"
    stdin_open: true
    tty: true
